### ISSUE TITLE
Differences with Redlock

### ISSUE THREAD

**Issue by antoinechalifour** [Julien-R44/verrou#3]
Hey 👋

I am currently using Redlock, but the library seems abandoned. I found Verrou and have a few questions that I think are not covered on the docs :

- how does it compare with Redlock ?
- how does it handle distributed locks ? (Multiple instances of the same server can request a lock)

Thanks,

Antoine

**Comment by Julien-R44** [comment]
Hey

the whole point of the library is to handle distributed locks. we also ship `in-memory` and `file-system` stores, which won't be suitable for multiple instance contexts. but other drivers: Database, Redis, Dynamo... handle distributed locks.

About Redlock, in the doc : https://verrou.dev/docs/drivers#implementation-details

we use this algorithm: https://redis.io/docs/manual/patterns/distributed-locks/#correct-implementation-with-a-single-instance

this is perfectly viable if you have a single instance of Redis. As explained in the Redis article, if you have several instances of Redis, its probably worth using the Redlock pattern and it's maybe something we'll add in a later version of Verrou. but since then I've never personally needed it

**Comment by antoinechalifour** [comment]
I totally missed that part, sorry about that.

Thanks a lot for your time and answer

**Comment by Julien-R44** [comment]
i just came across this: https://github.com/sesamecare/redlock a more modern version of redlock

i think we can wrap this package for integrating it in verrou at some point. i will have to take a closer look when time allows it

but in the meantime, if you need redlocks because of a multiple-redis environment, it could be a great replacement
